# generated by datamodel-codegen:
#   filename:  res.json
#   timestamp: 2022-06-28T20:15:07+00:00

from __future__ import annotations


from pydantic import BaseModel, Field


class Country(BaseModel):
    name: str
    code: str
    __typename: str


class Uri(BaseModel):
    path: str
    __typename: str


class City(BaseModel):
    id: str
    name: str
    __typename: str


class Location(BaseModel):
    id: str
    name: str
    city: City
    __typename: str


class FestivalSeasonEvent(BaseModel):
    id: str
    slug: str
    name: str
    is_highlighted: bool = Field(..., alias="isHighlighted")
    image_url: str = Field(..., alias="imageUrl")
    category: str
    start_date: str = Field(..., alias="startDate")
    end_date: str | None = Field(..., alias="endDate")
    available_tickets_count: int = Field(..., alias="availableTicketsCount")
    status: str
    artists: list
    country: Country
    uri: Uri
    location: Location
    __typename: str
